import argparse
import math
import os
from pathlib import Path
from typing import Dict, Iterable, List

import yaml


ANGLE_SUFFIXES = {
    0: "r0",
    90: "r90",
    180: "r180",
    270: "r270",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Rotate bottom contours in YAML files (generated by batch_obj_yaml_pipeline) "
            "around the Y-axis by 0/90/180/270 degrees and mirror the directory structure "
            "into an output folder with suffixes appended to filenames."
        )
    )
    parser.add_argument("input_dir", type=Path, help="Directory produced by batch_obj_yaml_pipeline")
    parser.add_argument("output_dir", type=Path, help="Directory to write rotated YAML files into")
    return parser.parse_args()


def iter_yaml_files(root: Path) -> Iterable[Path]:
    for dirpath, _dirnames, filenames in os.walk(root):
        for name in filenames:
            if name.lower().endswith(".yaml"):
                yield Path(dirpath) / name


def load_yaml_entries(yaml_path: Path) -> List[Dict]:
    with yaml_path.open("r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    if not isinstance(data, list):
        raise ValueError(f"Unexpected YAML structure in {yaml_path}")
    return data


def rotate_point(point: Iterable[float], angle_deg: int) -> List[float]:
    x, y, z = map(float, point)
    theta = math.radians(angle_deg)
    cos_t = math.cos(theta)
    sin_t = math.sin(theta)
    x_new = x * cos_t + z * sin_t
    z_new = -x * sin_t + z * cos_t
    return [x_new, y, z_new]


def rotate_contour(contour: Iterable[Iterable[float]], angle_deg: int) -> List[List[float]]:
    return [rotate_point(pt, angle_deg) for pt in contour]


def rotate_entries(entries: List[Dict], angle_deg: int) -> List[Dict]:
    rotated = []
    for entry in entries:
        if "bottom_contour" in entry:
            contour_key = "bottom_contour"
        elif "footprint" in entry:
            contour_key = "footprint"
        else:
            raise KeyError("Entry missing bottom contour key")

        contour = entry[contour_key]
        rotated_entry = dict(entry)
        rotated_entry[contour_key] = rotate_contour(contour, angle_deg)
        rotated.append(rotated_entry)
    return rotated


def write_rotated_yaml(entries: List[Dict], input_path: Path, output_root: Path, rel_path: Path, suffix: str) -> None:
    out_dir = (output_root / rel_path.parent).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{input_path.stem}_{suffix}.yaml"
    with out_path.open("w", encoding="utf-8") as f:
        yaml.safe_dump(entries, f, sort_keys=False)
    print(f"Saved {out_path}")


def main() -> None:
    args = parse_args()
    input_dir = args.input_dir.resolve()
    output_dir = args.output_dir.resolve()

    if not input_dir.exists():
        raise FileNotFoundError(f"Input directory {input_dir} does not exist")

    total_outputs = 0
    for yaml_path in iter_yaml_files(input_dir):
        rel_path = yaml_path.relative_to(input_dir)
        try:
            entries = load_yaml_entries(yaml_path)
        except Exception as exc:
            print(f"[ERROR] Failed to load {yaml_path}: {exc}")
            continue

        for angle, suffix in ANGLE_SUFFIXES.items():
            try:
                rotated_entries = rotate_entries(entries, angle)
            except Exception as exc:
                print(f"[ERROR] Failed to rotate {yaml_path} by {angle} deg: {exc}")
                break
            write_rotated_yaml(rotated_entries, yaml_path, output_dir, rel_path, suffix)
            total_outputs += 1

    print(f"Done. Generated {total_outputs} rotated YAML file(s).")


if __name__ == "__main__":
    main()
