[project]
name = "gendiff-data-process"
version = "0.2.0"
description = "DiffGen 数据规范化、构造与验证工具"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bpy>=4.5.4",
    "fpsample>=0.3.3",
    "pillow>=12.0.0",
    "pyyaml>=6.0.3",
    "trimesh[all]>=4.9.0",
    "tqdm>=4.66.0",
    "scipy>=1.16.3",
    "scikit-image>=0.25.2",
    "shapely>=2.1.2",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["gendiff_data_process*"]
